### ISSUE TITLE
Parser tests

### ISSUE THREAD

**Issue by MatthiesB** [HAW-MI-P1/FBSearch#7] opened 2015-01-13 19:20 UTC
Please fix your code in order to pass the newly added/enhanced jUnit tests. Most failures are about missing or wrong exceptions.

**Comment by lukasgr90** [comment] 2015-01-16 10:15
I'm not able to reproduce the bug.

Starting the test collection (de.haw.AllTests) all of our 20 parser tests are run successful.

**Comment by lukasgr90** [comment] 2015-01-16 10:18
Ok got it.

**Comment by lukasgr90** [comment] 2015-01-17 13:30
Should be fixed now.

**Closed by lukasgr90** 2015-01-17 13:30 UTC
